#PBS -S /bin/bash
#PBS -A ACF-UTK0011
#PBS -l partition=beacon
# #PBS -l feature=beacon_gpu
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -N DDPG_1-2_cutoff=1000

cd $PBS_O_WORKDIR

gamma=1
actor_lr=1
critic_lr=1
actor_layer=1
explore_noise=1
batch_size=32
drive_trace=IM240
max_episodes_buffer=1000
downweight_factor=2
SOC=10
epochs=5
cutoff=1000

conda activate ecocar
cd $PBS_O_WORKDIR

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nics/b/home/oqueen/.conda/envs/ecocar/lib/

for i in {1..2}
do
    python3 /lustre/haven/user/oqueen/EcoCAR/RL_Final_Project/ACC_RL/test_scripts/test_DDPG_general.py $gamma $actor_lr $critic_lr $actor_layer $explore_noise $batch_size $drive_trace $max_episodes_buffer $downweight_factor $SOC $epochs $cutoff DDPG_d=0.5_cutoff=10000/DDPG_$i $i DDPG_d=0.5_cutoff=10000_
done
